// Forward declarations for java.util
#pragma once


namespace java
{
    namespace util
    {
        class AbstractCollection;
        class AbstractList;
        class AbstractMap;
        class AbstractQueue;
        class AbstractSequentialList;
        class AbstractSet;
        class ArrayList;
        class Arrays;
        class Arrays_asList_2;
        class Arrays_sort_1;
        class BitSet;
        class BitSet_MaskInfo;
        class BitSet_MaskInfoIterator;
        class Calendar;
        class Calendar_MyCalendar;
        struct Collection;
        class Collections;
        class Collections_ArrayListIterator;
        class Collections_IteratorEnumeration;
        class Collections_KeyIterator;
        class Collections_ReverseComparator;
        class Collections_SynchronizedCollection;
        class Collections_SynchronizedIterator;
        class Collections_SynchronizedMap;
        class Collections_SynchronizedSet;
        class Collections_UnmodifiableList;
        class Collections_UnmodifiableMap;
        class Collections_UnmodifiableSet;
        class Collections_ValueIterator;
        struct Comparator;
        class ConcurrentModificationException;
        class Date;
        class EnumSet;
        class EnumSet_EnumSetIterator;
        struct Enumeration;
        struct EventListener;
        class EventObject;
        class HashMap;
        struct HashMap_Cell;
        class HashMap_EntrySet;
        struct HashMap_Helper;
        class HashMap_KeySet;
        class HashMap_MyCell;
        class HashMap_MyHelper;
        class HashMap_MyIterator;
        class HashMap_Values;
        class HashSet;
        class HashSet_MyIterator;
        class Hashtable;
        class IdentityHashMap;
        class IdentityHashMap_MyHelper;
        struct Iterator;
        class LinkedList;
        class LinkedList_Cell;
        class LinkedList_MyIterator;
        struct List;
        struct ListIterator;
        class Locale;
        struct Map;
        struct Map_Entry;
        class MissingResourceException;
        class NoSuchElementException;
        class Properties;
        class Properties_InputStreamParser;
        class Properties_Parser;
        class Properties_ReaderParser;
        class PropertyResourceBundle;
        struct Queue;
        class Random;
        struct RandomAccess;
        class ResourceBundle;
        struct Set;
        struct SortedSet;
        class Stack;
        class StringTokenizer;
        class TreeMap;
        class TreeMap_KeySet;
        class TreeMap_MyEntry;
        class TreeMap_TreeMap_1;
        class TreeMap_TreeMap_2;
        class TreeMap_Values;
        class TreeSet;
        class TreeSet_MyIterator;
        class TreeSet_TreeSet_1;
        class TreeSet_TreeSet_2;
        class UUID;
        class Vector;
        class WeakHashMap;
        class WeakHashMap_MyCell;
        class WeakHashMap_MyHelper;
    } // util
} // java
